channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - make
  - pip
  - pip:
    - --index-url=https://pypi.org/simple
    - --trusted-host=devopsartifact.jio.com
    - --trusted-host=pypi.org
    - --extra-index-url=${PIP_EXTRA_INDEX_URL}
    - -r requirements/dev.txt